apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgis
  namespace: croplands
  labels:
    app: croplands-db
spec:
  selector:
    matchLabels:
      app: croplands-db
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: croplands-db
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: croplands
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-postgres-user: "kv/devs/croplands"
        vault.hashicorp.com/agent-inject-secret-postgres-password: "kv/devs/croplands"
        vault.hashicorp.com/agent-inject-template-postgres-user: |
          {{- with secret "kv/devs/croplands" -}}
          {{ .Data.data.postgresAdminUser }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-postgres-password: |
          {{- with secret "kv/devs/croplands" -}}
          {{ .Data.data.postgresAdminPassword }}
          {{- end }}
    spec:
      serviceAccountName: croplands
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: postgres-prepare
          image: "eks-registry.prod-asc.chs.usgs.gov/dockerhub/library/alpine:latest"
          command:
          - rm
          - -rf
          - /var/lib/postgresql/data/lost+found
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: data

      containers:
        - name: postgres
          image: "eks-registry.prod-asc.chs.usgs.gov/dockerhub/usgsastro/postgis:12"
          env:
          - name: POSTGRES_USER_FILE
            value: /vault/secrets/postgres-user
          - name: POSTGRES_PASSWORD_FILE
            value: /vault/secrets/postgres-password
          ports:
          - containerPort: 5432
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: data

        - name: redis
          image: "eks-registry.prod-asc.chs.usgs.gov/dockerhub/library/redis:5"
          ports: [{ containerPort: 6379 }]

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi
